import Link from 'next/link';

export default function Guide() {
  return <main id="content" className="usage-guide"><Link href="/" className="back-link">Volver a Mis juegos</Link>
    <div className="page-heading"><div className="eyebrow">FORJA</div><h1>Guía de uso</h1><p>Crea tu juego, prepara cartas y llévalas a la mesa.</p></div>
    <section className="panel"><h2>1. Crear un juego y sus conceptos</h2><p>En Mis juegos, escribe un nombre y pulsa Crear juego. También puedes explorar Crear juego de ejemplo. Abre Configuración y crea tipos, sus subtipos y atributos. Un atributo compartido entre dos tipos aparece una sola vez en la carta. Añade supertipos, recursos y habilidades si los necesitas.</p>
    <h2>2. Crear, personalizar y guardar cartas</h2><p>En Cartas, pulsa Crear carta, escribe el nombre y elige sus tipos. Completa atributos, texto y habilidades. En Diseño elige la plantilla A o B, colores, ilustración, recorte y hasta cuatro espacios de atributos. Los atributos restantes aparecen en el texto. Guarda explícitamente y comprueba «Guardado en este navegador». Si una carta no cabe, corrige el texto antes de exportarla.</p>
    <h2>3. Escribir e imprimir el reglamento</h2><p>En Reglamento, escribe texto con párrafos y saltos de línea. Guardar reglamento conserva los cambios en el juego. Descargar reglamento PDF usa el texto visible, aunque todavía no lo hayas guardado. Elige Carta o A4. Descargar el PDF no guarda ni sustituye el respaldo del juego.</p>
    <h2>4. Preparar la tanda</h2><p>En Exportar / imprimir selecciona cartas y cantidades enteras positivas. Cero deselecciona. Elige Carta o A4, revisa las hojas y descarga el PDF de la selección. Cada frente mide 63 × 88 mm. El listado PDF contiene los nombres, cantidades y total de esa misma selección. También puedes descargar un PNG individual. La selección es temporal y se pierde al salir de esta vista.</p>
    <h2>5. Imprimir y comprobar medidas</h2><p>Imprime al 100 % o Tamaño real, sin Ajustar a página. Activa la hoja de calibración y mide el cuadrado de 50 × 50 mm y una carta de 63 × 88 mm entre centros de línea. Recorta una hoja de prueba antes de imprimir una tanda grande. Son solo frentes, para colocar en fundas con una carta de respaldo.</p><p><strong>Validación física pendiente:</strong> los archivos tienen comprobaciones digitales; la impresión, medición y recorte en papel deben confirmarse por separado.</p>
    <h2>6. Hacer respaldos y recuperar imágenes</h2><p>En Mis juegos, Exportar juego descarga un JSON con los datos guardados. Conserva también las imágenes originales por separado: el JSON no incluye sus bytes. Importar archivo JSON muestra un resumen y crea una copia independiente; nunca reemplaza el juego existente.</p><p>Después de importar, abre Imágenes pendientes en Cartas o Exportar / imprimir. Reasocia cada archivo o retira expresamente su referencia. Revisa la confirmación si su huella no coincide. Una carta sin ilustración es válida; una imagen pendiente debe resolverse antes de exportar sus frentes.</p>
    <h2>7. Dónde se guardan tus juegos</h2><p>Los juegos e imágenes se guardan en este navegador, perfil y origen del sitio, sin cuenta ni nube. Usa el mismo perfil y dirección al volver. Borrar los datos del sitio puede eliminarlos. El modo privado no es adecuado para conservar tu trabajo. Exporta respaldos periódicamente.</p><p>Localhost y el sitio publicado tienen bibliotecas separadas. Para trasladarte, exporta el JSON, impórtalo en la dirección nueva y reasocia las imágenes. Mantén la dirección publicada estable.</p><p>Si falla el guardado, conserva el formulario abierto y reintenta. El PDF del reglamento permite recuperar su texto visible, pero no reemplaza un respaldo JSON. Un conflicto entre pestañas exige revisar la versión guardada antes de descartar tu borrador.</p></section>
  </main>;
}
